version: '3.8'
services:

  postgresqldb:
    image: postgres:18.3-alpine
    environment:
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=shedlockdb
    ports:
      - "5432:5432"

