name: spring-boot-mongodb-elasticsearch

on:
  push:
    paths:
      - "spring-boot-mongodb-elasticsearch/**"
    branches: [main]
  pull_request:
    paths:
      - "spring-boot-mongodb-elasticsearch/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: spring-boot-mongodb-elasticsearch

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v3.5.1
        with:
          java-version: "19"
          distribution: "zulu"
          cache: "maven"
      - name: Start up redis via Docker Compose
        run: |
          cd docker
          docker-compose up -d
          sleep 5
          docker ps -a
      - name: Build with Maven
        run: ./mvnw clean verify package
